location_value = {
    'cmbsecc'                 :1000,
    'xining'                  :971,
    'haikou'                  :898,
    'beijing'                 :10,
    'changchun'               :431,
    'changsha'                :731,
    'chengdu'                 :28,
    'chongqing'               :23,
    'cmbleasing'              :1001,
    'dalian'                  :411,
    'dongguan'                :769,
    'foshan'                  :757,
    'fuzhou'                  :591,
    'guangzhou'               :20,
    'guiyang'                 :851,
	'hangzhou'                :571,
    'harbin'                  :451,
    'shenzhen_head_office'    :1007,
    'shanghai_head_office'    :1008,
    'hefei'                   :551,
    'hohhot'                  :471,
	'chengdu_hooc'            :1002,
	'shenzhen_hooc'           :1003,
	'shenzhen_itc'            :1004,
	'hangzhou_itc'            :1005,
	'shanghai_itc'            :1006,
    'jinan'                   :531,
    'kunming'                 :871,
    'lanzhou'                 :931,
    'nanchang'                :791,
    'nanjing'                 :25,
    'nanning'                 :771,
    'ningbo'                  :574,
    'qingdao'                 :532,
    'quanzhou'                :595,
    'shanghai'                :21,
	'shenyang'                :24,
    'shenzhen'                :755,
    'shijiazhuang'            :311,
    'singapore'               :1009,
    'suzhou'                  :512,
    'taiyuan'                 :351,
    'tangshan'                :315,
    'tianjin'                 :22,
    'training'                :1010,
    'urumqi'                  :991,
    'wenzhou'                 :577,
	'wuhan'                   :27,
    'wuxi'                    :510,
    'xiamen'                  :592,
    'xian'                    :29,
    'yinchuan'                :951,
    'zhengzhou'               :371,
	'shanghai_creidtcard'     :1011,
	'chengdou_creidtcard'     :1012,
	'wuhan_creidtcard'        :1013,
	'chengdou_callcenter'     :1014,
	'shanghai_zimao'          :1015,
	'futian_callcenter'       :1016,
	'shekou_kuaiji'           :1017,
	'chengdou_kuaiji'         :1018,
	'shekou_callcenter'       :1019,
    'global'                  :0
}

datacenter_value = {
    'SZ_ChinaTel_OA'    :10,
    'SH_ChinaTel_OA'    :12,
    'SH_ChinaTel_CBS'   :8,
    'SH_ChinaMob_NB'    :5,
    'SH_ChinaUni_CBS'   :9,
    'SH_ChinaUni_OA'    :13,
    'SZ_ChinaTel_NB'    :0,
    'BJ_ChinaUni_CDN'   :14,
    'SZ_ChinaUni_CBS'   :7,
    'SH_ChinaTel_NB'    :3,
    'SZ_ChinaUni_OA'    :11,
    'SZ_ChinaUni_NB'    :1,
    'SH_ChinaUni_NB'    :4,
    'SZ_ChinaTel_CBS'   :6,
    'SZ_Cernet_NB'      :2,
	'SH_OANet_NB'       :17,
	'SZ_OANet_NB'       :18,
	'SH_OANet_OA'       :19,
	'SZ_OANet_OA'       :20,
	'SH_OANet_CBS'      :21,
	'SZ_OANet_CBS'      :22,
	'SZ_ChinaMob_NB'    :16,
	'SZ_ChinaTel02_NB'  :15,
	'SH_ChinaTel02_NB'  :23,
	
}
priority_value = {
      0 : 9,
      1 : 8,
      2 : 7,
      3 : 6,
      4 : 5,
      5 : 4,
      6 : 3,
      7 : 2,
      8 : 1,
      9 : 0
}
